### ISSUE TITLE
Gem missing

### ISSUE THREAD

**Issue by djberg96** [ender672/ruby-vips#1]
I don't see ruby-vips in the default rubygems gem index, so I can't install it. Is it sitting in a different gem repo?

Regards,

Dan

**Comment by ender672** [comment]
No, it's not in another repo.

ruby-vips has just been kind of a mountain hermit, minding its own business, and only receiving the occasional close friend for brief visits.

Guess it's time to get it a little more accustomed to society. I'll give it a haircut tonight and see if I have a pair of shorts that will fit. Today or tomorrow I'll release to rubygems.org.

In the meantime, if you fetch the source you can build a gem quite easily. See the Readme for instructions. In any case I'll make sure to let you know when the gem is available.

**Comment by djberg96** [comment]
Yep, I cloned the repo and installed the gem. Easy.

I was trying to create a thumbnail from an existing image, but couldn't figure out how to set a specific height or width, only how to relatively resize it. How would you, say, take an existing image and resize it to 200x200? Or, just given a height or a width, resize it relative to its current size, e.g. I provide a height but no width (or vice-versa)?

**Comment by ender672** [comment]
This is where vips gets exciting - did I mention that it is a
low-level image library?

There are so many ways to make a thumbnail. If you want it done quick, maybe something like:

```
class VIPS::Image
  def thumbnail(x, y)
    width_ratio = x.to_f / x_size
    height_ratio = y.to_f / y_size
    ratio = [width_ratio, height_ratio].min
    shrink 1/ratio
  end
end
```

But there is so much more you can do with vips. Right now, the thumbnailer I am using looks like this:

module VIPS
      class Image
        SHARPEN_MASK = begin
          conv_mask = [
            [ -1, -1, -1 ],
            [ -1, 16, -1 ],
            [ -1, -1, -1 ]
          ]
          Mask.new conv_mask, 8
        end

```
    def self.thumbnail(src, width, height)
      if JPEGReader.recognized?(src)
        jpg = JPEGReader.new src
        ratio = get_ratio jpg, width, height
        jpg.shrink_factor = pre_shrink(ratio) if ratio <= 0.5

        im = jpg.read
      else
        im = Image.new src
      end

      im.thumbnail width, height
    end

    def thumbnail(width, height)
      ratio = get_ratio width, height

      if ratio > 1
        affinei_resize :nearest, ratio
      elsif ratio < 1
        im = self

        if ratio <= 0.5
          fast_shrink = (1/ratio).floor
          im = shrink fast_shrink
          ratio = im.get_ratio width, height
        end
        im = im.affinei_resize :bilinear, ratio unless ratio == 1
        im.conv SHARPEN_MASK
      end
    end

    def self.get_ratio(obj, tw, th)
      width_ratio = tw.to_f / obj.x_size
      height_ratio = th.to_f / obj.y_size
      [width_ratio, height_ratio].min
    end

    def get_ratio(*args); self.class.get_ratio self, *args; end

    private

    def self.pre_shrink(ratio)
      case (1/ratio)
      when (2...4) then 2
      when (4...8) then 4
      else 8
      end
    end
  end
end
```

Most image libraries do something similar to the above, but they hide it. And I bet you can do better than what I did right there.

Go ahead and make your own. Perhaps it will turn out looking better and running faster than any of the other thumbnailing routines out there.

**Comment by djberg96** [comment]
While I could make my own, I think it would be nicer if you provided that interface for your users. I can appreciate that it's a low level image library, but for people like me who want to perform relatively simple tasks, the interface is a bit daunting. By providing methods like "resize" (or whatever you want to call it), you make your library more accessible and, by extension, you will attract more users to your library. :)

In any case, thank you for your reply and code sample!

Regards,

Dan

**Comment by ender672** [comment]
Yes, I'm planning on building a higher-level library on top of ruby-vips. This will be a separate gem. I may be a little early with wearing the party hat and throwing confetti and all, but I am just so happy that ruby-vips is available now to build it on.

**Comment by djberg96** [comment]
Glad to hear it. Thanks!

Dan
