### ISSUE TITLE
Installation on Debian Lenny

### ISSUE THREAD

**Issue by eltiare** [ender672/ruby-vips#6]
For the life of me I can't figure out what bit of voodoo I have to perform to get this to work on Debian. I've tried all sorts of custom compiled versions of VIPS and the stock version that comes with Debian. Either the gem doesn't compile at all, or it bails during runtime with an error that it can't find a symbol or (more recently) that it can't find the .so file in the directory even though it's there. 

If I could get a little direction here that'd be wonderful.

**Comment by eltiare** [comment]
Sheesh. Never mind. I finally just updated a bunch of libraries & programs even though I was terrified it was going to bork something else on the server. Seems that + installing 4.22.7 did the trick. Does it work with 4.24?

**Comment by ender672** [comment]
I never tested on 4.24. You may have to update https://github.com/ender672/ruby-vips/blob/master/ext/extconf.rb to get it to compile.

**Comment by eltiare** [comment]
After I get over the nausea induced by the server installation incident I'll have to give it a try.
